sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6.5
before_install:
 - ls
 - cd test
 - ls
 - openssl aes-256-cbc -K $encrypted_8e63aafd52f0_key -iv $encrypted_8e63aafd52f0_iv -in test_exchanges.py.enc -out test_exchanges.py -
install:
  - pip install tox tox-travis
  - pip install coverage coveralls
  - pip install ccxt

script:
  - ls
  - cd test
  - ls
  - python --version
  - python sample_a.py
  - python -m unittest
